### ISSUE TITLE
[SDL3, CAMERA SUBSYSTEM] V4L2 backend refuses to recognize certain webcams.

### ISSUE THREAD

**Issue by eafton** [libsdl-org/SDL#13019]
I have two old but still functional webcams. SDL3 refuses to do anything with them no matter what.

For example, the "testcamera" program recgonizes none of them, even though both cameras are recognized and functional in any other application (the V4L2 utilities, inxi, GNOME Cheese, etc)

Here is the console output from testcamera: 
```
everett@mediaplex:~/Desktop/SDL3-3.2.12/b/test$ ./testcamera 
Using SDL camera driver: v4l2
Saw 0 camera devices.
No cameras available?
```

Console output from v4l2-ctl: 
```
everett@mediaplex:~/Desktop/SDL3-3.2.12/b/test$ v4l2-ctl --list-devices
PC Camera (usb-0000:02:00.0-2.1):
	/dev/video1

USB camera (usb-0000:02:00.0-2.2):
	/dev/video0
```
Console output from inxi: 
```
everett@mediaplex:~/Desktop/SDL3-3.2.12/b/test$  inxi -G
Graphics:
  Device-1: AMD Juniper XT [Radeon HD 6770] driver: radeon v: kernel
  Device-2: Z-Star Micro ZC0303 Webcam type: USB driver: gspca_zc3xx
  Device-3: Microdia Win2 PC Camera type: USB driver: sonixj
```

I think SDL3 does not recognize these cameras because they are pre-UVC models that only support MJPEG output, but I could be wrong.
I used the latest stable SDL3 release (3.2.12) on Debian 12, My apologizes if this issue has been already fixed in the main branch.
