### ISSUE TITLE
Compiling SDL2 (release-2.0.16) fails with ClangCL from VS2019 because of "-idirafter" flag

### ISSUE THREAD

**Issue by jonesmz** [libsdl-org/SDL#4702]
See this part of the cmake configuration

```
if(USE_GCC OR USE_CLANG)
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -idirafter \"${SDL2_SOURCE_DIR}/src/video/khronos\"")
else()
  include_directories(${SDL2_SOURCE_DIR}/src/video/khronos)
endif()
```

> clang-cl : warning : unknown argument ignored in clang-cl: '-idirafter' [-Wunknown-argument] [D:\a\osp-magnum\osp-magnum\build\3rdparty\SDL2\SDL2.vcxproj]
>   error: error reading 'D:/a/osp-magnum/osp-magnum/3rdparty/SDL2/src/video/khronos'

You should be able to reproduce this failure with a simple github action.

```
name: Windows

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
	fetch-depth: 1
        submodules: recursive

    - name: Build
      run: |
	cmake -B build -DCMAKE_BUILD_TYPE=Release -TClangCL
	cmake --build build --parallel --config Release
```
