### ISSUE TITLE
GitHub Actions should just build Linux, Mac, Windows per-push and PR

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#6624]
> GitHub Actions should just build Linux, Mac, Windows as fast as possible per commit and PR, and once a day/hour/whatever we should do all builds, and things like static analysis and clang-tidy, etc.
>
> This gets us really fast feedback when working and lets us do more janitorial work from time to time. Right now it takes way too long to do a basic sanity check on a commit.

_Originally posted by @icculus in https://github.com/libsdl-org/SDL/issues/3519#issuecomment-1325553525_

**Comment by madebr** [comment]
As a 2nd tier goal, I think it would be nice to be able to trigger (all) workflows when some condition is met.
e.g. when somebody opens a pr concerning ps2, (at least) the ps2 workflow should run

**Comment by shish** [comment]
> when somebody opens a pr concerning ps2, (at least) the ps2 workflow should run

For reference, you can filter triggers by paths like:

```yaml
on:
  pull_request:
    paths:
    - '**/ps2/*'
```

You can also enable a manual trigger button on the GitHub Actions GUI like so:
```yaml
on:
  workflow_dispatch:
```

So if we replaced `ps2.yaml`'s current
```yaml
on: [push, pull_request]
```
with 
```yaml
on:
  push:
  pull_request:
    paths:
    - '**/ps2/*'
    - '.github/workflows/ps2.yaml'
  workflow_dispatch:
```
Then that would run:
- on any push to the main repo
- on any pull request that touches PS2-specific files
- when the workflow itself is changed (debugging the workflows themselves is a pain without this...)
- when triggered manually (eg if you have a PR which doesn't touch PS2 files, but you want to test it on PS2 anyway)
