### ISSUE TITLE
USB controller is connected but has no inputs

### ISSUE THREAD

**Issue by genericptr** [libsdl-org/SDL#6686]
Following my discussion at https://discourse.libsdl.org/t/sdl-joysticknumbuttons-always-returns-0/40357/10 I have wired NES USB controller which upon receiving a `SDL_JOYDEVICEADDED` event is returning:

```YAML
SDL_JoystickName: USB Gamepad
SDL_JoystickGetAttached: TRUE
SDL_JoystickNumButtons: 0
SDL_JoystickNumHats: 0
SDL_JoystickNumAxes: 0
SDL_IsGameController: FALSE
```

I'm running macOS 13 on an M1 Pro and SDL 2.24.1. The  controller works using emulators and `gamepad-tool` shows it correct and gets button presses.

![](https://discourse.libsdl.org/uploads/default/original/2X/6/6c1bd7fa554d6db4c5550f1ba8f05e4c170ea60b.jpeg)
