### ISSUE TITLE
Provide a cross-platform way to use SDL in other projects's GitHub Actions

### ISSUE THREAD

**Issue by icculus** [libsdl-org/SDL#7219]
This might already have a simple solution, but something I've run into several times now:

- You have an app that uses SDL
- You want to turn on CI for that app
- On the Ubuntu build machines, you just apt-get install libsdl2-dev before you build your own app.
- On macOS and Windows: giant question mark. Try to figure out how to download a build, give up and just leave Linux as the only build target for CI.

It'd be nice if there were some clear way to say "make sure SDL is available for building my app on GitHub Actions," which might be some tool people can reference from their CI .yml file, or just a line in the README somewhere that says "do this magic incantation and then CMake will find SDL on Windows and macOS" ...anything is fine if it reduces the friction here.

**Comment by flibitijibibo** [comment]
A few samples from my end:

- https://github.com/TerryCavanagh/VVVVVV/blob/master/.github/workflows/ci.yml
- https://github.com/FNA-XNA/FNA3D/blob/master/.github/workflows/ci.yml
- https://github.com/FNA-XNA/FAudio/blob/master/.github/workflows/ci.yml

Windows is actually the easiest, you download the zip and define the extract path when telling CMake where the includes and libs are. macOS uses brew, which is fast but not as instant as downloading a prebuilt binary. Linux is the one I think is the hardest; VVV uses a CentOS Docker image, FNA3D uses a PPA, and Linux uses linuxbrew (seriously).

If we wanted to get Linux on the same level as macOS we could make an official libsdl-org PPA and update it after a tag, again it wouldn't be instant but it'd be pretty close. Either way, that'd be enough for us to automate all three into modules that people could import into their own Actions files (for example, the homebrew `uses` lines in the above samples.

**Comment by ericoporto** [comment]
> do this magic incantation and then CMake will find SDL

If building from source is alright, you can use FetchContent + add subdirectory, it should work anywhere.

**Comment by flibitijibibo** [comment]
The build VMs are pretty slow though, and the minutes can add up pretty quickly for private repositories - for static linking it makes sense but for dynamic it's tough enough trimming off seconds for the _supported_ VMs :/

**Comment by slouken** [comment]
*nod*

**Comment by icculus** [comment]
> Linux is the one I think is the hardest; VVV uses a CentOS Docker image, FNA3D uses a PPA, and FAudio uses linuxbrew 

On Linux, I just `apt-get install libsdl2-dev` in the default Ubuntu that GitHub provides, because generally in third-party apps, I just need a generic "SDL2" API and not the bleeding edge (ymmv!), and that was super-easy.

https://github.com/icculus/DirkSimple/blob/main/.github/workflows/main.yml#L16-L20

I was thinking it might make sense to have a little script or .yml or whatever that says "download the latest release from libsdl.org's webpage, and unzip it in a reasonable place, then just make sure you run CMake with -DSDL_INCLUDE_PATH=where/i/unzipped/it"

It doesn't have to be a perfect setup for good binary compatibility, we just want it to be something that can compile and link successfully and then be thrown away. Something easy to copy/paste into a thing.

Also, it's wild that this isn't something GitHub Actions has a trivial way to automate already.

**Comment by ericoporto** [comment]
I am unfortunately more experienced in CirrusCi than GitHub Actions, but what I usually do is have the fetch content + add subdirectory AND the option of simply using find_package (using `-DUSE_LOCAL_SDL2=1`), which gives me flexibility locally. But on CI, I leverage Docker (Linux and Windows) or the CI Cache. 

As @flibitijibibo mentions, the seconds/minutes on CI are precious, by using [Cache Action][1] it should be possible to build from source and store the results or get from a package manager and store the results. This could be a [Composite Action][2], which would be cross platform.

[1]: https://github.com/actions/cache
[2]: https://docs.github.com/en/actions/creating-actions/about-custom-actions#composite-actions

**Comment by madebr** [comment]
How about creating a `setup-sdl` GitHub action with the following high-level behavior:
```yml
name: "Setup SDL"
description: "Set up SDL and add the path of SDLx.dll to the PATH (if platform is Windows)."
inputs:
  version:
    description: "Required version of SDL (2.x.y, 2-latest, 2-HEAD, 3-HEAD)"
    default: "2-latest"
    required: true
    # 2.x.y: version 2.x.y
    # 2-latest:  latest SDL2 release
    # 2-head: latest SDL2 main
    # 3-head: latest SDL3 main
  cmake_toolchain:
    description: "Path of CMake toolchain file"
outputs:
  root:
    description: "The root of the SDL package"
  pkgconfig:
    description: "Folder containing sdlx.pc"
    
steps:
   1. Calculate corresponding SDL git hash of ${{inputs.version}}
   2. Summarize the compiler so we are somewhat confident the cache will fetch the correct cached SDLx
      if inputs.cmake_toolchain is None:
        - on Windows, assume MSVC
          (compiler_props={compiler: "MSVC", version: ${version}, os: Windows})
        - on Linux+Macos: if set, use env.CC/env.CXX. Else, use /usr/bin/cc and /usr/bin/c++.
          (compiler_props={compiler: {cc_version: $(cc --version), cxx_version: $(c++ --version), cflags: env.CFLAGS, cxxflags: env.CXXFLAGS})
      else:
        - use toolchain file
          (compiler_props=${cmake_toolchain: READ(${{inputs.cmake_toolchain}})})
   2. Calculate cache-key: "sdl-setup-" + HASH({
        os: ${{runner.os}},
        compiler_props: ${compiler_props},
        sdl_version: $corresponding_git_hash,
      })
   3. Try fetching cached setup-sdl
   4. if cache hit:
         extract cache to /setup-sdl/$corresponding_git_hash/package
         GOTO STEP 12
   5. fetch SDL commit $corresponding_git_hash to SRCDIR=/setup-sdl/$corresponding_git_hash/src 
   6. Ensure existance of CMake toolchain file (create one for the case where none was passed in inputs.cmake_toolchain)
   7. Setup ninja
   8. Execute "cmake -S $SRCDIR -B/setup-sdl/$corresponding_git_hash/build -DCMAKE_TOOLCHAIN_FILE=$setupsdl_cmake_toolchain_file -GNinja -DSDL_SHARED=ON -DSDL_STATIC=ON -DSDL_TEST=ON -DSDL_TESTS=OFF -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_INCLUDEDIR=include -DCMAKE_PREFIX_PATH=/setup-sdl/$corresponding_git_hash/package"
   9. Execute "cmake --build /setup-sdl/$corresponding_git_hash/build"
  10. Execute "cmake --install /setup-sdl/$corresponding_git_hash/build"
  11. Cache /setup-sdl/$corresponding_git_hash/package
  12. if github.runner == "Windows":
         add C:\setup-sdl\$corresponding_git_hash\package\bin to PATH
  13. set outputs.root=\setup-sdl\$corresponding_git_hash\package
  13. set outputs.pkg_config=\setup-sdl\$corresponding_git_hash\package\lib\pkgconfig
``` 

- It uses caching to speed up subsequent use (some effort is done to make sure compilers aren't mixed)
- By providing a "cmake_toolchain" option, you can modify it
- When nothing is passed, it uses the default system toolchain
- By setting PATH, tests requiring SDLx.dll should succeed.
- The sdl_root/pkg_config output can be used in subsequent steps
- This proposal does not install SDL in a system folder. So subsequent steps need to refer to outputs.sdl_root.
  Is this a problem?
