### ISSUE TITLE
file(RELATIVE_PATH bin_prefix_relpath ...) fails when run with microsoft/msvc-code-analysis-action@v0.1.1

### ISSUE THREAD

**Issue by jonesmz** [libsdl-org/SDL#8447]
```
file(RELATIVE_PATH bin_prefix_relpath "${CMAKE_INSTALL_FULL_BINDIR}" "${CMAKE_INSTALL_PREFIX}")
```
generates the error 
```
CMake Error at 3rdparty/SDL2/CMakeLists.txt:3087 (file):
  file RELATIVE_PATH must be passed a full path to the directory:
  win64sdk/bin
```
See github action run here: https://github.com/jonesmz/osp-magnum/actions/runs/6687943837/job/18169278376

Workflow is
```
  analyze-windows:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        tool: [msvc-code-analysis]
        config: [Release, Debug]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Configure (MSVC)
      run: |
        cmake -B build -DCMAKE_CONFIGURATION_TYPES=${{ matrix.config }}

    - name: Initialize MSVC Code Analysis
      uses: microsoft/msvc-code-analysis-action@v0.1.1
      # Provide a unique ID to access the sarif output path
      id: run-analysis
      with:
        cmakeBuildDirectory: build
        buildConfiguration: ${{ matrix.config }}
        # Ruleset file that will determine what checks will be run
        ruleset: NativeRecommendedRules.ruleset
        ignoredPaths: 3rdparty
        ignoredIncludePaths: 3rdparty

      # Upload SARIF file to GitHub Code Scanning Alerts
    - name: Upload SARIF to GitHub
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.run-analysis.outputs.sarif }}
```

Apparently the msvc-code-analysis-action is changing the installation prefix?
